version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./volume_data:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    ports:
      - '9000:9000'
    volumes:
      - ./volume_files:/var/www/html
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    ports:
      - '443:443'
    volumes:
      - ./volume_files:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    name: inception