version: '3.8'

services:
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9001:9000
    env_file:
      - .env
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    restart: on-failure
    init: true
    networks:
      - inception
  vsftpd:
    build: ./requirements/bonus/vsftpd
    container_name: vsftpd
    image: vsftpd
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 20-21:20-21
      - 30000-30009:30000-30009
    env_file:
      - .env
    restart: on-failure
    init: true
    networks:
      - inception
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - wordpress_data:/data
    restart: on-failure
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/bonus/dots:/var/www/dots
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    name: inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/axbrisse/data/mariadb_data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/axbrisse/data/wordpress_data
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/axbrisse/data/portainer_data