version: '3.8'

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./volume_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always
    networks:
      - inception
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    ports:
      - '9000:9000'
    volumes:
      - ./volume_files:/var/www/html
    environment:
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./volume_files:/var/www/html
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    name: inception